### ISSUE TITLE
请问这个后续有 升级go 1.14 计划吗？

### ISSUE THREAD

**Issue by gamegg** [lonng/nanoserver#13]
请问这个后续有 升级go 1.14 计划吗？

**Comment by lonng** [comment]
你可以直接使用 1.14 编译，没有什么问题的。

**Comment by gamegg** [comment]
报好多错额；

go  1.14


runtime: bad pointer in frame github.com/konsorten/go-windows-terminal-sequences.EnableVirtualTerminalProcessing at 0xc000107670: 0x250
fatal error: invalid pointer found on stack

runtime stack:
runtime.throw(0xc63212, 0x1e)
        D:/Go/src/runtime/panic.go:1116 +0x79 fp=0x14cf790 sp=0x14cf760 pc=0x437019
runtime.adjustpointers(0xc000107670, 0x14cf890, 0x14cfc20, 0xec74b8, 0x1222860)
        D:/Go/src/runtime/stack.go:599 +0x22e fp=0x14cf7f0 sp=0x14cf790 pc=0x44dbde
runtime.adjustframe(0x14cfb30, 0x14cfc20, 0x1222860)
        D:/Go/src/runtime/stack.go:641 +0x355 fp=0x14cf8c0 sp=0x14cf7f0 pc=0x44df45
runtime.gentraceback(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc000041080, 0x0, 0x0, 0x7fffffff, 0xc871e8, 0x14cfc20, 0x0, ...)
        D:/Go/src/runtime/traceback.go:334 +0x111c fp=0x14cfb98 sp=0x14cf8c0 pc=0x45aabc
runtime.copystack(0xc000041080, 0x4000)
        D:/Go/src/runtime/stack.go:888 +0x298 fp=0x14cfd50 sp=0x14cfb98 pc=0x44e668
runtime.newstack()
        D:/Go/src/runtime/stack.go:1043 +0x219 fp=0x14cfee0 sp=0x14cfd50 pc=0x44e939
runtime.morestack()
        D:/Go/src/runtime/asm_amd64.s:449 +0x97 fp=0x14cfee8 sp=0x14cfee0 pc=0x464037

goroutine 7 [copystack]:
runtime.concatstring2(0xc0001073a0, 0xc52342, 0xc, 0xc497cb, 0x1, 0x0, 0x0)
        D:/Go/src/runtime/string.go:57 +0x71 fp=0xc000107368 sp=0xc000107360 pc=0x450401
syscall.UTF16FromString(0xc52342, 0xc, 0x2030000, 0x2030000, 0xd4ee2e, 0x0, 0xc00004f520)

**Comment by gamegg** [comment]
> 你可以直接使用 1.14 编译，没有什么问题的。

报好多错额；

go 1.14

runtime: bad pointer in frame github.com/konsorten/go-windows-terminal-sequences.EnableVirtualTerminalProcessing at 0xc000107670: 0x250
fatal error: invalid pointer found on stack

runtime stack:
runtime.throw(0xc63212, 0x1e)
D:/Go/src/runtime/panic.go:1116 +0x79 fp=0x14cf790 sp=0x14cf760 pc=0x437019
runtime.adjustpointers(0xc000107670, 0x14cf890, 0x14cfc20, 0xec74b8, 0x1222860)
D:/Go/src/runtime/stack.go:599 +0x22e fp=0x14cf7f0 sp=0x14cf790 pc=0x44dbde
runtime.adjustframe(0x14cfb30, 0x14cfc20, 0x1222860)
D:/Go/src/runtime/stack.go:641 +0x355 fp=0x14cf8c0 sp=0x14cf7f0 pc=0x44df45
runtime.gentraceback(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc000041080, 0x0, 0x0, 0x7fffffff, 0xc871e8, 0x14cfc20, 0x0, ...)
D:/Go/src/runtime/traceback.go:334 +0x111c fp=0x14cfb98 sp=0x14cf8c0 pc=0x45aabc
runtime.copystack(0xc000041080, 0x4000)
D:/Go/src/runtime/stack.go:888 +0x298 fp=0x14cfd50 sp=0x14cfb98 pc=0x44e668
runtime.newstack()
D:/Go/src/runtime/stack.go:1043 +0x219 fp=0x14cfee0 sp=0x14cfd50 pc=0x44e939
runtime.morestack()
D:/Go/src/runtime/asm_amd64.s:449 +0x97 fp=0x14cfee8 sp=0x14cfee0 pc=0x464037

goroutine 7 [copystack]:
runtime.concatstring2(0xc0001073a0, 0xc52342, 0xc, 0xc497cb, 0x1, 0x0, 0x0)
D:/Go/src/runtime/string.go:57 +0x71 fp=0xc000107368 sp=0xc000107360 pc=0x450401
syscall.UTF16FromString(0xc52342, 0xc, 0x2030000, 0x2030000, 0xd4ee2e, 0x0, 0xc00004f520)

**Comment by lonng** [comment]
看起来这个依赖有问题，我会尽快修复这个问题。

**Comment by gamegg** [comment]
> 看起来这个依赖有问题，我会尽快修复这个问题。

好的 谢谢~！

**Comment by youmisun** [comment]
> > 你可以直接使用 1.14 编译，没有什么问题的。
> 
> 报好多错额；
> 
> go 1.14
> 
> runtime: bad pointer in frame github.com/konsorten/go-windows-terminal-sequences.EnableVirtualTerminalProcessing at 0xc000107670: 0x250
> fatal error: invalid pointer found on stack
> 
> runtime stack:
> runtime.throw(0xc63212, 0x1e)
> D:/Go/src/runtime/panic.go:1116 +0x79 fp=0x14cf790 sp=0x14cf760 pc=0x437019
> runtime.adjustpointers(0xc000107670, 0x14cf890, 0x14cfc20, 0xec74b8, 0x1222860)
> D:/Go/src/runtime/stack.go:599 +0x22e fp=0x14cf7f0 sp=0x14cf790 pc=0x44dbde
> runtime.adjustframe(0x14cfb30, 0x14cfc20, 0x1222860)
> D:/Go/src/runtime/stack.go:641 +0x355 fp=0x14cf8c0 sp=0x14cf7f0 pc=0x44df45
> runtime.gentraceback(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc000041080, 0x0, 0x0, 0x7fffffff, 0xc871e8, 0x14cfc20, 0x0, ...)
> D:/Go/src/runtime/traceback.go:334 +0x111c fp=0x14cfb98 sp=0x14cf8c0 pc=0x45aabc
> runtime.copystack(0xc000041080, 0x4000)
> D:/Go/src/runtime/stack.go:888 +0x298 fp=0x14cfd50 sp=0x14cfb98 pc=0x44e668
> runtime.newstack()
> D:/Go/src/runtime/stack.go:1043 +0x219 fp=0x14cfee0 sp=0x14cfd50 pc=0x44e939
> runtime.morestack()
> D:/Go/src/runtime/asm_amd64.s:449 +0x97 fp=0x14cfee8 sp=0x14cfee0 pc=0x464037
> 
> goroutine 7 [copystack]:
> runtime.concatstring2(0xc0001073a0, 0xc52342, 0xc, 0xc497cb, 0x1, 0x0, 0x0)
> D:/Go/src/runtime/string.go:57 +0x71 fp=0xc000107368 sp=0xc000107360 pc=0x450401
> syscall.UTF16FromString(0xc52342, 0xc, 0x2030000, 0x2030000, 0xd4ee2e, 0x0, 0xc00004f520)

我将go mod 里的github.com/sirupsen/logrus v1.1.0 换成 github.com/sirupsen/logrus v1.6.0就可以了

**Comment by gamegg** [comment]
> > > 你可以直接使用 1.14 编译，没有什么问题的。
> > 
> > 
> > 报好多错额；
> > go 1.14
> > runtime: bad pointer in frame github.com/konsorten/go-windows-terminal-sequences.EnableVirtualTerminalProcessing at 0xc000107670: 0x250
> > fatal error: invalid pointer found on stack
> > runtime stack:
> > runtime.throw(0xc63212, 0x1e)
> > D:/Go/src/runtime/panic.go:1116 +0x79 fp=0x14cf790 sp=0x14cf760 pc=0x437019
> > runtime.adjustpointers(0xc000107670, 0x14cf890, 0x14cfc20, 0xec74b8, 0x1222860)
> > D:/Go/src/runtime/stack.go:599 +0x22e fp=0x14cf7f0 sp=0x14cf790 pc=0x44dbde
> > runtime.adjustframe(0x14cfb30, 0x14cfc20, 0x1222860)
> > D:/Go/src/runtime/stack.go:641 +0x355 fp=0x14cf8c0 sp=0x14cf7f0 pc=0x44df45
> > runtime.gentraceback(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc000041080, 0x0, 0x0, 0x7fffffff, 0xc871e8, 0x14cfc20, 0x0, ...)
> > D:/Go/src/runtime/traceback.go:334 +0x111c fp=0x14cfb98 sp=0x14cf8c0 pc=0x45aabc
> > runtime.copystack(0xc000041080, 0x4000)
> > D:/Go/src/runtime/stack.go:888 +0x298 fp=0x14cfd50 sp=0x14cfb98 pc=0x44e668
> > runtime.newstack()
> > D:/Go/src/runtime/stack.go:1043 +0x219 fp=0x14cfee0 sp=0x14cfd50 pc=0x44e939
> > runtime.morestack()
> > D:/Go/src/runtime/asm_amd64.s:449 +0x97 fp=0x14cfee8 sp=0x14cfee0 pc=0x464037
> > goroutine 7 [copystack]:
> > runtime.concatstring2(0xc0001073a0, 0xc52342, 0xc, 0xc497cb, 0x1, 0x0, 0x0)
> > D:/Go/src/runtime/string.go:57 +0x71 fp=0xc000107368 sp=0xc000107360 pc=0x450401
> > syscall.UTF16FromString(0xc52342, 0xc, 0x2030000, 0x2030000, 0xd4ee2e, 0x0, 0xc00004f520)
> 
> 我将go mod 里的github.com/sirupsen/logrus v1.1.0 换成 github.com/sirupsen/logrus v1.6.0就可以了

感谢！~

**Comment by lonng** [comment]
@youmisun 你能提交一个 PR 更新这个日志库吗

**Comment by AnkoGo** [comment]
我怎么使用go mod无法拉取到你的这个项目？好奇怪！希望支持go1.14，可以给个大概时间吗？比较急！

**Comment by lonng** [comment]
可以，很简单，我来吧

**Comment by lonng** [comment]
PR https://github.com/lonng/nanoserver/pull/14 合并了，你看看现在能拉到吗？
